### ISSUE TITLE
use our metatables in qgep_sys to do the matching and not hardcode it.

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#10]
@olivierdalang When exporting the demodata with INTERLIS Export I get the following errors when checking the export.xtf:

![export_interlis_demoprojekt_fehler](https://user-images.githubusercontent.com/1265865/114771372-c01bac80-9d6c-11eb-9122-c2904135b1eb.jpg)

How do you do the matching?
Via the vl_* tables:?

There I can find the missing values

![vl_structure_renovation_necessity](https://user-images.githubusercontent.com/1265865/114756980-9a39dc00-9d5b-11eb-9022-d9be5f85f474.jpg)
![vl_wastewater_structure_structure_condition](https://user-images.githubusercontent.com/1265865/114756984-9ad27280-9d5b-11eb-9fe8-ebd197a12943.jpg)

**Comment by olivierdalang** [comment]
(moved this issue here)

@sjib Is this comment still valid ?

If so I'd need a little bit more explanation on how these tables relate to the vl_* tables (to me it looks like it duplicates most information, unsure why even they exist for values ?) as well as on what the benefit would be ? Or are you suggesting that in case we need to implement translation ourselves (if ili2pg doesn't handle it) ?

**Comment by olivierdalang** [comment]
Closing this

@sjib feel free to reopen if you think it's still valid
