### ISSUE TITLE
Check if adapted file path is valid

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#2]
If I change the file path it should check whether the file path is valid and has e.g. backslash at end and uses wanted slash (backslash or slashes - which one is better for different systems (Linux, Windows, ...)

![testdata_vsa_kek_2019_manhole_damage_8486_identifierref_009_21052021_104531](https://user-images.githubusercontent.com/1265865/119116073-307eb300-ba28-11eb-9538-20a91b02571f.jpg)

Original path: "D:/DVD_Laufwerk/" with ending /

![testdata_vsa_kek_2019_manhole_damage_8486_identifierref_012_21052021_104854](https://user-images.githubusercontent.com/1265865/119112575-818ca800-ba24-11eb-84fb-f0ba39db7f08.jpg)

Adapted path: "C:\temp\2019\vsakek\inspectiondata20210120 " - uses \ instead of / and not ending slash

Also empty spaces at the end should be deleted. 

Question: Should this be implemented on the datamodel side or in this wizard?

**Comment by olivierdalang** [comment]
In the wizard, we could check if the path exists on the host, but then it could easily happen that you're importing data without necessarily having access to the final location of the files (e.g. because not connected to the network, or because an external hard drive is not plugged in). So it would really just be an informative non-blocking warning.

Also I'd suggest we don't add too much validation/intelligence, as there are potentially many edge cases (remote URLs, including with get paramters, etc.). Also it's very easy to adapt afterwards anyways in case the user didn't get it perfectly right on import.

**Comment by olivierdalang** [comment]
Implemented check if the path exists and is a valid directory on the current system. Did not additional checks due to reasons above.

Feel free to reopen this if you still think we should add more checks.
