### ISSUE TITLE
Log not shown on sucessful export

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#44]
When an export is successful the export log is not displayed and has to be locked up in the protocol/qgep tab:

![gep_export_selection_wastewater_structures_success](https://user-images.githubusercontent.com/1265865/131689160-d3532ef0-c605-45b2-8aa7-3f5adad99869.jpg)
![gep_export_selection_wastewater_structures_success_log_not_shown](https://user-images.githubusercontent.com/1265865/131689169-00980a0e-8d01-43a9-b93a-95a14adc83a5.jpg)

@ponceta @urskaufmann 

- [ ] Do you think this is ok or would you like to have the log in the same directory as the xtf export data? 

- [ ] Or would we need to be able to set the log path also in the plugin (as in the command line tool?). 
Any preferences?

Example of sucessful log (selecting wastewater structures): 
[ili2qgepqwat-2021-09-01-16-21-01-validate.zip](https://github.com/QGEP/qgepqwat2ili/files/7091927/ili2qgepqwat-2021-09-01-16-21-01-validate.zip)

**Comment by urskaufmann** [comment]
same directory as xtf: as default (filename with date and time stamp)
set the log path (default as above): nice to have, I'm not sure if I will use it...

**Comment by ponceta** [comment]
A copy of the log could be created in the export repository. 👍 

For debugging purposes I find it easier to have it directly in QGIS plugin log window.

AS soon as it won't be an experimental version, I would be in favor of minimal logs at least on qgis side.

**Comment by olivierdalang** [comment]
I've added a button to the logs on successful export (same as on failure).

About where to save logs, we could add a setting in the QGEP plugin for to choose for that behavior, but the more settings, the more issues/maintenance. Adding to confusion, there's already some logging settings for QGEP, that we can't really reuse directly, as they are thought to log to just one file, while we have multiple files to which we want to log (so we keep separated logs for ili2db). 

So I suggest we find a consensus (also easier to help each other if it works in the same way for everybody) rather than add options.

IMO, the current behavior (saving to `%temp%/ili2qgepqwat` / `/tmp`) is nice because it avoid creating many files that one must manually cleanup and that can be quite big (hundreds of megs for full ilidb export logs).

I suggest we keep that behavior when used from the GUI, as you now get a button to open the logs folder directly, so that it doesn't matter too much where they are. From the command line it's still possible to add the `--log` flag to determine that.

If that's fine with you, I'm closing this as the root issue is now fixed. If you agree on a different logging strategy, we can open a feature issue for a future improvement.
