### ISSUE TITLE
Missing Attribute Rohrleitungsteil.Art

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#47]
There is currently no matching defined from qwat to Rohrleitungsteil.Art

CLASS Rohrleitungsteil EXTENDS Leitungsknoten =  
!! Rohrleitungsteil

   ATTRIBUTE

    Name_Nummer: TEXT*40;
    Art: (     

      Verbindungselement (
        unbekannt,
         Ueberschieber_Schlaufe,
         Reparaturschelle,
         Weldend,
         Anbohrung (
            normal,
            blind,
            gekehrt
         )
      ),
      Formstueck (
         unbekannt,
         Reduktion (
            normal,
            Reduzierflansch,
            Reduzierkupplung
         ),
         Bogen  (
            horizontal,  !! Falls horizontale Differenz des Bogens > vertikale Differenz
            vertikal  !! Falls vertikale Differenz des Bogens > horizonatel Differenz
         ),
           Kompensator,
         T_Stueck,
         Kreuzstueck,
         Anschlussstueck
      ),
      Anbohrschelle (
         normal,
         blind,
         gekehrt
      ),
      Abschlusselement (
         unbekannt,
         Kappe_Blindflansch,
         Blindflansch,
         Zapfen,
         Verschlussklappe
      ),
      Lueftung (
         auf_Rohr,
         auf_Formstueck_Armatur
      ),
      Diverse (
         unbekannt,
         Isolierstueck,
         Drucksonde_Gleichrichter,
         Rueckflussverhinderer,
         Zaehler,
         Standardschacht,
         Druckminderventil
      ),
      Standrohr
    );

https://github.com/QGEP/qgepqwat2ili/blob/bc0f3f429734f6b2e45603fe28d0b63cb2221ab7/qgepqwat2ili/qwat/export.py#L240

Where would we have to add this matching?

**Comment by sjib** [comment]
![qgis_visualisierung_qwat_demo_xtf_rohrleitungsteil_attribute](https://user-images.githubusercontent.com/1265865/132004637-7d59c2e6-cb1a-4778-b3cc-01d316642cbc.jpg)

**Comment by olivierdalang** [comment]
Currently, the export script only creates rohrleitungsteil objects for nodes without network_element, because it's not possible to match directly to leitungsknoten since it is abstract.

This also means that there's no attributes that we can really match to that (since we're mapping a very generic node object to a quite specific rohrleitungsteil object).

IMO, unless there's a better match than rohrleitungsteil to represent these generic nodes, the current behaviour is correct.

I'll remove the TODO in the code so it's less misleading, and close that for now. Please reopen the issue if you can think of a better implementation.
