### ISSUE TITLE
fk_pressure_zone is NULL

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#49]
Technicall corect as attribute Druckzone is MANDATORY in INTERLIS:
`CLASS Leitung EXTENDS SIA405_Base.SIA405_BaseClass =  `

`!! Leitung`
 
 `ATTRIBUTE`
 `    ...`
`     Druckzone: MANDATORY TEXT*30;`

`sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) FEHLER:  NULL-Wert in Spalte »druckzone« verletzt Not-Null-Constraint
DETAIL:  Fehlgeschlagene Zeile enthält (34759, 38884, 01090000200808000001000000010200000007000000CB7BAB7D9F8A4341BFE7..., Bau_Wasseranschluss, unbekannt, null, null, null, None, Trinkwasser, unbekannt, in_Betrieb, 1800, null, null, null, offener_Graben, null, null, null, unbekannt, null, null, null, 16.0, null, 45, null, in_Betrieb, null, Privé, null, null, Tracé inconnu, null).

[SQL: INSERT INTO pg2ili_wasser.leitung (t_id, name_nummer, geometrie, funktion, material, durchmesserinnen, durchmesseraussen, durchmesser, nennweite, wasserqualitaet, lagebestimmung, astatus, baujahr, verbindungsart, aussenbeschichtung, innenbeschichtung, verlegeart, schubsicherung, ueberdeckung, sanierung_erneuerung, bettung, kathodischer_schutz, druckzone, zulaessiger_bauteil_betriebsdruck, betriebsdruck, hydraulische_rauheit, laenge, unterhalt, zustand, eigentuemer, betreiber, konzessionaer, unterhaltspflichtiger, bemerkung, strangref) VALUES (%(t_id)s, %(name_nummer)s, ST_ForceCurve(ST_RemoveRepeatedPoints(ST_Force2D(ST_Transform(ST_GeomFromEWKB(%(ST_GeomFromEWKB_1)s), %(ST_Transform_1)s)), %(ST_RemoveRepeatedPoints_1)s)), %(funktion)s, %(material)s, %(durchmesserinnen)s, %(durchmesseraussen)s, %(durchmesser)s, %(nennweite)s, %(wasserqualitaet)s, %(lagebestimmung)s, %(astatus)s, %(baujahr)s, %(verbindungsart)s, %(aussenbeschichtung)s, %(innenbeschichtung)s, %(verlegeart)s, %(schubsicherung)s, %(ueberdeckung)s, %(sanierung_erneuerung)s, %(bettung)s, %(kathodischer_schutz)s, %(druckzone)s, %(zulaessiger_bauteil_betriebsdruck)s, %(betriebsdruck)s, %(hydraulische_rauheit)s, %(laenge)s, %(unterhalt)s, %(zustand)s, %(eigentuemer)s, %(betreiber)s, %(konzessionaer)s, %(unterhaltspflichtiger)s, %(bemerkung)s, %(strangref)s)]
[parameters: {'t_id': 34759, 'name_nummer': '38884', 'ST_GeomFromEWKB_1': <memory at 0x0000021051EC6948>, 'ST_Transform_1': 2056, 'ST_RemoveRepeatedPoints_1': 0.002, 'funktion': 'Bau_Wasseranschluss', 'material': 'unbekannt', 'durchmesserinnen': None, 'durchmesseraussen': None, 'durchmesser': None, 'nennweite': 'None', 'wasserqualitaet': 'Trinkwasser', 'lagebestimmung': 'unbekannt', 'astatus': 'in_Betrieb', 'baujahr': 1800, 'verbindungsart': None, 'aussenbeschichtung': None, 'innenbeschichtung': None, 'verlegeart': 'offener_Graben', 'schubsicherung': None, 'ueberdeckung': None, 'sanierung_erneuerung': None, 'bettung': 'unbekannt', 'kathodischer_schutz': None, 'druckzone': None, 'zulaessiger_bauteil_betriebsdruck': None, 'betriebsdruck': 16, 'hydraulische_rauheit': None, 'laenge': Decimal('44.97'), 'unterhalt': None, 'zustand': 'in_Betrieb', 'eigentuemer': None, 'betreiber': 'Privé', 'konzessionaer': None, 'unterhaltspflichtiger': None, 'bemerkung': 'Tracé inconnu', 'strangref': None}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)`

![qwat_pipe fk_pressurezone_is_null](https://user-images.githubusercontent.com/1265865/132567606-ebea1661-2967-48a4-890e-5938c64c910a.jpg)

@ponceta @kandre Can you always connect a pipe to a pressurezone or do you need to have a dataset "unknown" in the table pressurezone? Is this a data error that needs to be corrected?

**Comment by ponceta** [comment]
@sjib yes, this is a dataset error because every pipe and water structure element should be over a pressure zone and assigned to it.

But we saw with @3nids that it can be tricky to draw pressure zones multi polygons for just one pipe from another network crossing the main pressure zone.

You can see here under a sample of the complexity it can be to manage correctly pressure zones and not mentionning what it implies for maintenance if you have to draw a new pipe (actually you should correct the pressure zone even before adding a new pipe). I actually define it more as art or jewellry but it actually works fine for now.

![image](https://user-images.githubusercontent.com/8614223/132630337-018b7226-94bd-416b-aaf4-52cd37dc20c8.png)

This was meant to ease the automatisation of pressure zone selection for the user and it works quite well actually. We will see how complex it will be in Pully when we will change some of the pressure zones organisation.

Nota bene : a new QWAT user should draw its pressure zones before importing any data in QWAT.

That's all why we didn't set fk_pressure_zone as mandatory

![image](https://user-images.githubusercontent.com/8614223/132631314-aed81631-650d-4a02-b4f2-eb7175352e3b.png)

In Pully we only have few pipes in the case of a NULL pressure zone and these wouldn't have much sense in an SIA 405 export ( tuyaux d'arrosages pour les jardins de la ville, les terrains de foot, ...)

**Comment by olivierdalang** [comment]
For now, I'll set the druckzone to `unknown` if the pipe has no relation, so that they don't prevent the export / validation.

Alternatively we could set it to `` (empty string), so that it the export is complete, but still recongnized as  nvalid as per ilivalidator. Please reopen if you prefer that alternative behaviour.
