### ISSUE TITLE
Documentation of tests missing

### ISSUE THREAD

**Issue by sjib** [QGEP/qgepqwat2ili#85]
Please describe the [tests](https://github.com/QGEP/qgepqwat2ili/tree/master/qgepqwat2ili/tests) and the used [testdata](https://github.com/QGEP/qgepqwat2ili/tree/master/qgepqwat2ili/data/test_data)

It looks like some testdata is intended to create failures - but then tests are not running thru:
![test_qgep py](https://user-images.githubusercontent.com/1265865/204372816-cecb6297-c4f3-4dba-bcdc-36a5284682d6.jpg)

is this intended or not?

Currently code cannot be checked in without errors - see e.g. https://github.com/QGEP/qgepqwat2ili/pull/84

**Comment by olivierdalang** [comment]
If I remember correctly, this is because the input XTF we had to test import at the time of implementing this was not valid (according to ilivalidator). If we have a better file now (ideally something a shareable real-world like file), it would be good to use it instead of `case_c_import_all.xtf` and remove the `@unittest.expectedFailure` line

**Comment by sjib** [comment]
See https://github.com/QGEP/qgepqwat2ili/pull/84#issuecomment-1380886261
